services:
    spa:
        build:
            context: .
            dockerfile: Dockerfile.prod
        container_name: fe-vite-container
        ports:
            - '5173:80'
        restart: unless-stopped
